# Generated by Django 5.1.4 on 2025-01-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_writeblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeblog',
            name='title',
            field=models.CharField(max_length=240),
        ),
    ]
